### ISSUE TITLE
--processing-scheme mkl is not working

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#108]
Using `pycbc_inspiral --processing-scheme mkl` does not appear to work on master.

On sugar-dev3:
```
source ~/lalsuite/heads/lalsuite-v6.29_20150520_dfc6a/etc/lscsoftrc
source ~/pycbc/master_20150626/etc/pycbc-user-env.sh
cd /home/cbiwer/projects/pycbc_test_arg_fix/gw/work/main_ID0000001
pycbc_inspiral  --segment-end-pad 16 --cluster-method window --low-frequency-cutoff 40 --pad-data 8 --cluster-window 1.0 --sample-rate 4096 --injection-window 1.0 --segment-start-pad 64 --psd-segment-stride 8 --psd-inverse-length 16 --filter-inj-only  --psd-segment-length 16 --processing-scheme mkl --snr-threshold 5.0 --segment-length 512 --approximant SPAtmplt --newsnr-threshold 5.0 --psd-estimation median --keep-loudest-num 100 --strain-high-pass 30 --keep-loudest-interval 2 --order 7 --chisq-bins 128 --channel-name L1:LDAS-STRAIN --gps-start-time 966388166 --gps-end-time 966390406 --trig-start-time 966388230 --trig-end-time 966389982 --output  96638/L1-INSPIRAL_FULL_DATA-966388230-1752.hdf  --frame-files  96638/L-T1200307_V4_EARLY_RECOLORED_V2-966385664-4096.gwf   96638/L-T1200307_V4_EARLY_RECOLORED_V2-966389760-4096.gwf  --bank-file  BNS_NonSpin_30Hz_earlyaLIGO.xml --verbose
```

Gives:
```
Traceback (most recent call last):
  File "/home/cbiwer/pycbc/master_20150626/bin/pycbc_inspiral", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===e95439', 'pycbc_inspiral')
  File "/home/cbiwer/.local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cbiwer/.local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/cbiwer/pycbc/master_20150626/lib/python2.6/site-packages/PyCBC-e95439-py2.6.egg/EGG-INFO/scripts/pycbc_inspiral", line 190, in <module>
    segments = strain_segments.fourier_segments()
  File "/home/cbiwer/pycbc/master_20150626/lib/python2.6/site-packages/PyCBC-e95439-py2.6.egg/pycbc/strain.py", line 596, in fourier_segments
    freq_seg = make_frequency_series(self.strain[seg_slice])
  File "/home/cbiwer/pycbc/master_20150626/lib/python2.6/site-packages/PyCBC-e95439-py2.6.egg/pycbc/filter/matchedfilter.py", line 274, in make_frequency_series
    fft(vec, vectilde)   
  File "/home/cbiwer/pycbc/master_20150626/lib/python2.6/site-packages/PyCBC-e95439-py2.6.egg/pycbc/fft/__init__.py", line 182, in fft
    thebackend = backends_dict[backends_list[0]]
IndexError: list index out of range
```

If I remove the `--processing-scheme` it keeps running.

**Comment by ahnitz** [comment]
Chris,

How are you sourcing the MKL libraries?

**Comment by ahnitz** [comment]
I you do,

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/ahnitz/local/mkl/lib64

Do you get the same results?

**Comment by cmbiwer** [comment]
Ah I thought there was a system version of MKL now where I didn't have to source anything.

I guess this is not a bug but rather me mucking around.

Adding your LD_LIBRARY_PATH works.

**Comment by ahnitz** [comment]
The error message is bad though. I should fix that.

**Comment by lppekows** [comment]
This is installed system-wide, but you still need to do

  source /opt/intel/bin/compilervars.sh intel64

to use it.

**Comment by cmbiwer** [comment]
Thanks Larne, that's what I need.
