### ISSUE TITLE
WaveformArray errors with inference output if not sampling in mass1,mass2,spin1x,etc.

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#1140]
If you sample in `mchirp`, `q`, `spin1_a`, `spin1_azimuthal`, etc. then the `WaveformArray` class doesn't know how to return `mass1`, `m_p`, etc. since it assumes it has `mass1`, `spin1x`, etc. and calculates the virtualfields.

`WaveformArray` should be able to map `mchirp`, `q` to `mass1`,`mass2` or `m_p`,`m_s` and likewise for spherical to Cartesian spins.

This affects all the inference post-processing code, eg. `pycbc_inference_plot_posterior` error I get when I sample in `mchirp`,`q` but want to plot `mass1`:

```
Traceback (most recent call last):
  File "/home/cbiwer/opt/pycbc-dev/bin/pycbc_inference_plot_posterior", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==84a103', 'pycbc_inference_plot_posterior')
  File "/home/cbiwer/opt/pycbc-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 746, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cbiwer/opt/pycbc-dev/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1501, in run_script
    exec(code, namespace, namespace)
  File "/home/cbiwer/opt/pycbc-dev/lib/python2.7/site-packages/PyCBC-84a103-py2.7.egg/EGG-INFO/scripts/pycbc_inference_plot_posterior", line 76, in <module>
    x[:,ii] = samples[p]
  File "/home/cbiwer/opt/pycbc-dev/lib/python2.7/site-packages/PyCBC-84a103-py2.7.egg/pycbc/io/record.py", line 821, in __getitem__
    return eval(item, {"__builtins__": None}, item_dict)
  File "<string>", line 1, in <module>
NameError: name 'mass1' is not defined
```

**Comment by cmbiwer** [comment]
PR #1596 fixes this once its merged.

**Comment by cmbiwer** [comment]
Closing this now.
