### ISSUE TITLE
Edge case in pycbc_page_snrratehist

### ISSUE THREAD

**Issue by stevereyes01** [ligo-cbc/pycbc#1247]
I encountered a bug in `pycbc_page_snrratehist`

```
/home/steven.reyes/pycbc_page_snrratehist_hacked --trigger-file /home/steven.reyes/projects/cbc/ER10/rerunDuncanER10ConfigsSEOBNRv4/Analysis1-ReRun-Chi-Bug/output/local-site-scratch/work/./O1-Analysis1-ER10Settings-main_ID0000001/./H1L1-STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_12H_FULL_DATA_FULL_BIN_1-1126051217-1220400.hdf  --output-file  H1L1-PLOT_SNRRATEHIST_FULL_DATA_FULL_CUMULATIVE_CAT_12H_FULL_DATA_FULL_BIN_1-1126051217-1220400.png 
```

```
Traceback (most recent call last):
  File "/home/steven.reyes/pycbc_page_snrratehist_hacked", line 130, in <module>
    weights=dec_exc / f.attrs['background_time_exc'] * lal.YRJUL_SI)
  File "/home/steven.reyes/pycbc-dev/lib/python2.7/site-packages/matplotlib/pyplot.py", line 2965, in hist
    stacked=stacked, data=data, **kwargs)
  File "/home/steven.reyes/pycbc-dev/lib/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/home/steven.reyes/pycbc-dev/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 6106, in hist
    minimum = (np.min(ndata[ndata > 0])) / logbase
  File "/home/steven.reyes/pycbc-dev/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2397, in amin
    out=out, **kwargs)
  File "/home/steven.reyes/pycbc-dev/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

See https://github.com/ligo-cbc/pycbc/blob/v1.5.7/bin/hdfcoinc/pycbc_page_snrratehist#L71-L89 for the offending lines.

The edge case I think that's occurring here is that the code is trying to build a histogram where the loudest foreground trigger is louder than the entire background AND there is only one foreground trigger in the bin. In this case the bounds for the histogram are set at the minimum is set to the foreground trigger which is louder than the background. Then the maximum is set to the max between foreground triggers and background triggers, which makes the histogram maximum bound the same as its minimum bound. (This is GW150914 in the edge bin of analysis 1 by the way)

The code then tries to calculate bins to span between the minimum and maximum + bin_width. Unfortunately, using numpy.arange() to bin up the space for the histogram returns one bin since numpy.arange is inclusive on one bound and exclusive on the other. The plotting code then tries to make a step histogram with one bin.

I've tried reproducing this error with a simple histogram code, where the error is generated by having only one bin in a step histogram, but on further reflection this may not be the cause of this error. I've tried hacking the code to make it run with more bins (say 100 bins), but that doesn't seem to solve this issue.

**Comment by stevereyes01** [comment]
See https://github.com/ligo-cbc/pycbc/pull/1254
