### ISSUE TITLE
pycbc_coinc_mergetrigs should report which open failed

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1291]
``pycbc_coinc_mergetrigs`` calls ``data = h5py.File(filename, 'r')`` to open the input HDF5 files, but if this fails the underling h5py library does not actually print the name of the offending file. ``pycbc_coinc_mergetrigs`` should catch ``IOError`` print the name of the file, and re-throw the error.

```
__init__: Setting weave cache to /var/lib/condor/execute/dir_3541856/43628_python27_compiled/1.5.10/
2016-11-29 06:25:57,839 : getting the list of columns from a representative file
2016-11-29 06:25:57,841 : trigger column: bank_chisq
2016-11-29 06:25:57,842 : trigger column: bank_chisq_dof
2016-11-29 06:25:57,842 : trigger column: chisq
2016-11-29 06:25:57,842 : trigger column: chisq_dof
2016-11-29 06:25:57,842 : trigger column: coa_phase
2016-11-29 06:25:57,842 : trigger column: cont_chisq
2016-11-29 06:25:57,842 : trigger column: cont_chisq_dof
2016-11-29 06:25:57,842 : trigger column: end_time
2016-11-29 06:25:57,843 : trigger column: sigmasq
2016-11-29 06:25:57,843 : trigger column: snr
2016-11-29 06:25:57,843 : trigger column: template_duration
2016-11-29 06:25:57,843 : reading the metadata from the files
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.5.10/bin/pycbc_coinc_mergetrigs", line 74, in 
    data = h5py.File(filename, 'r')
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.5.10/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.5.10/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (File signature not found)
```

**Comment by duncan-brown** [comment]
The patch needs to be changed as the code will no longer fail if a HDF5 file is corrupted, which could cause us to lose triggers. See:

https://github.com/ligo-cbc/pycbc/commit/fdb68316f8fb7237f6e1b9a7e9f0c8d507254236

**Comment by duncan-brown** [comment]
Fixed by https://github.com/ligo-cbc/pycbc/pull/1304
