### ISSUE TITLE
Changing value of a readonly variable

### ISSUE THREAD

**Issue by pannarale** [ligo-cbc/pycbc#14]
Bumped into this using an old ini-file: once I cleaned up and fixed the ini-file, I did not hit this problem again.  Having said that, it looks like line 106 of timeseries.py tries to change the value of a readonly variable, which should not be happening.

Traceback (most recent call last):
  File "/home/francesco.pannarale/opt/pycbc//bin/pycbc_inspiral" line 120, in <module>
    segments = strain_segments.fourier_segments()
  File "/home/francesco.pannarale/opt/pycbc/lib/python2.6/site-packages/pycbc/strain.py", line 587, in fourier_segments
    freq_seg = make_frequency_series(self.strain[seg_slice])
  File "/home/francesco.pannarale/opt/pycbc/lib/python2.6/site-packages/pycbc/types/timeseries.py", line 106, in __getitem__
    index.start += len(self)
TypeError: readonly attribute

**Comment by ahnitz** [comment]
I've made a patch to convert this to an explicit error. If that is satisfactory, I'll push that change.

**Comment by pannarale** [comment]
This is more informative.  Looks good to me, go ahead and push.
