### ISSUE TITLE
Problem with weave compiles in multi-core codes

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1425]
I am still seeing weave compiles tripping over each other in compute_psd multicore jobs. @ahnitz, I think the quick solution is just to add a ``psd()`` before the multiprocesing so that it's pre-compiled?

```
 /cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.6.4/lib/python2.7/site-packages/pycbc/types/array.py:354: RuntimeWarning: divide by zero encountered in divide
  return self._data.__rdiv__(other)
/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.6.4/lib/python2.7/site-packages/pycbc/types/array.py:354: RuntimeWarning: divide by zero encountered in divide
  return self._data.__rdiv__(other)
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.6.4/bin/pycbc_calculate_psd", line 100, in 
    psds = psds.get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
scipy.weave.build_tools.CompileError: error: Command "g++ -pthread -shared -Wl,-z,relro /var/lib/condor/execute/dir_15013/scipy-dbrown-pR2Y7S/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/var/lib/condor/execute/dir_15013/620_python27_compiled/1.6.4/50719056/sc_0824510149a0cf3967b746b0273477930.o /var/lib/condor/execute/dir_15013/scipy-dbrown-pR2Y7S/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.6.4/lib/python2.7/site-packages/scipy/weave/scxx/weave_imp.o -L/usr/lib64 -lpython2.7 -o /var/lib/condor/execute/dir_15013/620_python27_compiled/1.6.4/50719056/sc_0824510149a0cf3967b746b0273477930.so" failed with exit status 1
creating /var/lib/condor/execute/dir_15013/scipy-dbrown-pR2Y7S/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2
/var/lib/condor/execute/dir_15013/scipy-dbrown-pR2Y7S/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.6.4/lib/python2.7/site-packages/scipy/weave/scxx/weave_imp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
/var/lib/condor/execute/dir_15013/scipy-dbrown-pR2Y7S/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.6.4/lib/python2.7/site-packages/scipy/weave/scxx/weave_imp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
```

**Comment by duncan-brown** [comment]
It looks like it's doing this, so I'm not sure why it's failing:

https://github.com/ligo-cbc/pycbc/blob/master/bin/hdfcoinc/pycbc_calculate_psd#L97

Certainly, I can just increase the number of times condor tries this job, as it gets picked up on a re-run.

**Comment by duncan-brown** [comment]
```
[dbrown@CRUSH-SUGWG-OSG-10-5-148-240 1.6.4]$ pwd
/var/lib/condor/execute/dir_68824/620_python27_compiled/1.6.4
[dbrown@CRUSH-SUGWG-OSG-10-5-148-240 1.6.4]$ ls -lR 
.:
total 20
drwxr-x--- 2 dbrown lsc 4096 Feb  8 06:44 44483920
drwxr-x--- 2 dbrown lsc 4096 Feb  8 06:45 74815440
drwxr-x--- 2 dbrown lsc 4096 Feb  8 06:45 74815568
drwxr-x--- 2 dbrown lsc 4096 Feb  8 06:45 74815696
drwxr-x--- 2 dbrown lsc 4096 Feb  8 06:45 74815824

./44483920:
total 400
-rw-r----- 1 dbrown lsc      0 Feb  8 06:44 code_lockfile
-rw-r----- 1 dbrown lsc  12288 Feb  8 06:44 linux227compiled_catalog
-rw-r----- 1 dbrown lsc  26281 Feb  8 06:44 sc_0824510149a0cf3967b746b0273477930.cpp
-rwxr-x--- 1 dbrown lsc 169288 Feb  8 06:44 sc_0824510149a0cf3967b746b0273477930.so
-rw-r----- 1 dbrown lsc  24951 Feb  8 06:44 sc_fded9885ef54da8de785c3ccab719a980.cpp
-rwxr-x--- 1 dbrown lsc 165424 Feb  8 06:44 sc_fded9885ef54da8de785c3ccab719a980.so

./74815440:
total 400
-rw-r----- 1 dbrown lsc      0 Feb  8 06:45 code_lockfile
-rw-r----- 1 dbrown lsc  12288 Feb  8 06:45 linux227compiled_catalog
-rw-r----- 1 dbrown lsc  26281 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.cpp
-rwxr-x--- 1 dbrown lsc 169288 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.so
-rw-r----- 1 dbrown lsc  24951 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.cpp
-rwxr-x--- 1 dbrown lsc 165488 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.so

./74815568:
total 400
-rw-r----- 1 dbrown lsc      0 Feb  8 06:45 code_lockfile
-rw-r----- 1 dbrown lsc  12288 Feb  8 06:45 linux227compiled_catalog
-rw-r----- 1 dbrown lsc  26281 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.cpp
-rwxr-x--- 1 dbrown lsc 169288 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.so
-rw-r----- 1 dbrown lsc  24951 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.cpp
-rwxr-x--- 1 dbrown lsc 165424 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.so

./74815696:
total 400
-rw-r----- 1 dbrown lsc      0 Feb  8 06:45 code_lockfile
-rw-r----- 1 dbrown lsc  12288 Feb  8 06:45 linux227compiled_catalog
-rw-r----- 1 dbrown lsc  26281 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.cpp
-rwxr-x--- 1 dbrown lsc 169288 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.so
-rw-r----- 1 dbrown lsc  24951 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.cpp
-rwxr-x--- 1 dbrown lsc 165424 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.so

./74815824:
total 400
-rw-r----- 1 dbrown lsc      0 Feb  8 06:45 code_lockfile
-rw-r----- 1 dbrown lsc  12288 Feb  8 06:45 linux227compiled_catalog
-rw-r----- 1 dbrown lsc  26281 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.cpp
-rwxr-x--- 1 dbrown lsc 169288 Feb  8 06:45 sc_0824510149a0cf3967b746b0273477930.so
-rw-r----- 1 dbrown lsc  24951 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.cpp
-rwxr-x--- 1 dbrown lsc 165424 Feb  8 06:45 sc_fded9885ef54da8de785c3ccab719a980.so
```

**Comment by duncan-brown** [comment]
Needs more debugging, but for the time being I modified the ini file to just keep trying:
```
[pegasus_profile-calculate_psd]
condor|+InitialRequestMemory = 8000
condor|request_cpus = ${calculate_psd|cores}
dagman|priority = 1000
dagman|retry = 10
```

**Comment by duncan-brown** [comment]
@josh-willis does https://github.com/ligo-cbc/pycbc/pull/1661 fix this issue?

**Comment by josh-willis** [comment]
Hi Duncan,

I'm not sure.  From the logfile you posted, it looked like the lockfiles were being created, whereas with the bug my patch fixed, they weren't.  The problem I was seeing was when independent inspiral jobs were on the same node (I was trying to load up the node for benchmarking) rather than one process that was multithreaded. Have you tried this on current master to see if the problem goes away?

**Comment by duncan-brown** [comment]
@ahnitz updating this with the issue I just posted in chat. As of PyCVC 1.7.9, this issue is still fixed. The temporary workaround in O2 was to increase the number of retries for the multi-core jobs that use weave. Here is an example of a [calculate psd job failing](https://sugwg-osg.phy.syr.edu/pegasus/u/dbrown/r/516/w/2/j/141340/ji/107876) and then succeeding on the second retry.

Pegasus dashboard had a bug in this run that means that the ``stdout`` and ``stderr`` for the failing job were not capture correctly, but here is the ``stderr``:
```
Traceback (most recent call last):
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.7.9/bin/pycbc_calculate_psd", line 4, in &lt;module&gt;
    __import__('pkg_resources').run_script('PyCBC==1.7.9', 'pycbc_calculate_psd')
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1503, in run_script
    exec(code, namespace, namespace)
  File "/cvmfs/oasis.opensciencegrid.org/ligo/deploy/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.7.9/lib/python2.7/site-packages/PyCBC-1.7.9-py2.7.egg/EGG-INFO/scripts/pycbc_calculate_psd", line 100, in &lt;module&gt;
    psds = psds.get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
weave.build_tools.CompileError: error: Command "g++ -pthread -shared -Wl,-z,relro /var/lib/condor/execute/dir_3992934/weave-dbrown-J34y20/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/var/lib/condor/execute/dir_3992934/620_python27_compiled/none/none/83298960/sc_fded9885ef54da8de785c3ccab719a980.o /var/lib/condor/execute/dir_3992934/weave-dbrown-J34y20/python27_intermediate/compiler_8d209134f2f9c02590a11606fa273eb2/cvmfs/oasis.opensciencegrid.org/ligo/sw/pycbc/x86_64_rhel_7/virtualenv/pycbc-v1.7.9/lib/python2.7/site-packages/weave/scxx/weave_imp.o -L/usr/lib64 -lgomp -lpython2.7 -o /var/lib/condor/execute/dir_3992934/620_python27_compiled/none/none/83298960/sc_fded9885ef54da8de785c3ccab719a980.so" failed with exit status 1
```

The pegasus kickstart script that ran this job is attached.

[calculate_psd-PART1-H1_ID106_ID0035326.txt](https://github.com/ligo-cbc/pycbc/files/1467524/calculate_psd-PART1-H1_ID106_ID0035326.txt)

**Comment by duncan-brown** [comment]
@dethodav please can you post the error you are getting with ``pycbc_live`` here?

**Comment by dethodav** [comment]
Possibly related to this weave issue, two different failures are occurring in `pycbc_live`. The first occurs once filtering starts, complaining about a `/tmp` file being too short: 
```
Traceback (most recent call last):
  File "/home/derek.davis/src/pycbc/bin/pycbc_live", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==12a597', 'pycbc_live')
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/EGG-INFO/scripts/pycbc_live", line 437, in <module>
    results[ifo] = mf.process_data(data_reader[ifo])
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/filter/matchedfilter.py", line 1362, in process_data
    return self.process_all()
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/filter/matchedfilter.py", line 1369, in process_all
    result, veto = self._process_batch()
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/filter/matchedfilter.py", line 1455, in _process_batch
    sgm = htilde.sigmasq(psd)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/waveform/bank.py", line 84, in sigma_cached
    self._sigmasq[key] = self.sigma_view.inner(psd.invsqrt)
  File "<decorator-gen-71>", line 2, in inner
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/types/array.py", line 278, in _vrcheckother
    return fn(self, *nargs) # pylint:disable=not-callable
  File "<decorator-gen-70>", line 2, in inner
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/types/array.py", line 65, in _convert
    return fn(self, *args)
  File "<decorator-gen-69>", line 2, in inner
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/scheme.py", line 184, in scheming_function
    return schemed_fn(*args, **kwds)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/types/array_cpu.py", line 145, in inner
    return inner_inline_real(self, other)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/PyCBC-12a597-py2.7.egg/pycbc/types/array_cpu.py", line 135, in inner_inline_real
    extra_compile_args=code_flags)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/weave/inline_tools.py", line 366, in inline
    **kw)
  File "/home/derek.davis/src/pycbc/lib/python2.7/site-packages/weave/inline_tools.py", line 502, in compile_function
    exec('import ' + module_name)
  File "<string>", line 1, in <module>
ImportError: /tmp/50002_python27_compiled/none/none/sc_2107325a10e2db4369323937223875580.so: file too short
```

The second happens during the bank generation, complaining of `g++` issues:
```
weave.build_tools.CompileError: error: Command "g++ -pthread -shared -Wl,-z,relro /tmp/weave-derek.davis-Tc14El/python27_intermediate/compiler_1f4c5631ffc914638955edc8c1da3934/tmp/50002_python27_compiled/none/none/sc_8ac50855f43f26429ce465e79758bdf21.o /tmp/weave-derek.davis-Tc14El/python27_intermediate/compiler_1f4c5631ffc914638955edc8c1da3934/home/derek.davis/src/pycbc/lib/python2.7/site-packages/weave/scxx/weave_imp.o -L/usr/lib64 -lgomp -lpython2.7 -o /tmp/50002_python27_compiled/none/none/sc_8ac50855f43f26429ce465e79758bdf21.so" failed with exit status 1
```

**Comment by ahnitz** [comment]
@duncan-brown @dethodav Please try this PR https://github.com/ligo-cbc/pycbc/pull/1977

**Comment by ahnitz** [comment]
I consider this closed now. Re-open a new issue if things reappear.
