### ISSUE TITLE
Emcee sampling is broken

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#1625]
I haven't used this sampler in awhile but its broken now.

I can use it before PR #1308 where I tried commit ``9aff59fe`` and it works.

Then I tried PR #1536 (ie. commit ``35d65a7``) and I get this error:
```
Traceback (most recent call last):
  File "/home/cbiwer/opt/pycbc-dev3/bin/pycbc_inference", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===9aff59', 'pycbc_inference')
  File "/home/cbiwer/opt/pycbc-dev3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cbiwer/opt/pycbc-dev3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/home/cbiwer/opt/pycbc-dev3/lib/python2.7/site-packages/PyCBC-9aff59-py2.7.egg/EGG-INFO/scripts/pycbc_inference", line 359, in <module>
    sampler.run(end-start)
  File "/home/cbiwer/opt/pycbc-dev3/lib/python2.7/site-packages/PyCBC-9aff59-py2.7.egg/pycbc/inference/sampler_emcee.py", line 417, in run
    res = self._sampler.run_mcmc(pos, niterations, **kwargs)
  File "build/bdist.linux-x86_64/egg/emcee/sampler.py", line 172, in run_mcmc
  File "build/bdist.linux-x86_64/egg/emcee/ptsampler.py", line 261, in sample
ValueError: setting an array element with a sequence.
```

Same as master now.

Any idea what's going on here? It was tested?

**Comment by cmbiwer** [comment]
I have an example on sugwg: ``/home/cbiwer/projects/inference_samples_group/test/run_pycbc_inference.sh``

**Comment by cdcapano** [comment]
@ahnitz Can you take a look?

**Comment by ahnitz** [comment]
@cdcapano @cmbiwer Yes, I'll take a look.

**Comment by ahnitz** [comment]
@cmbiwer The emcee sampler still works, but I'm investigating the PT sampler. I can reproduce the error, so that's a start.

**Comment by ahnitz** [comment]
@cmbiwer @cdcapano. The PT sampler is not working because it is relying on setting a *class* variable *after* the pool is created. This is not possible with the multiprocessing module. Specifically, this has no effect. https://github.com/ligo-cbc/pycbc/blob/master/pycbc/inference/sampler_emcee.py#L286
