### ISSUE TITLE
Travis upgrade to Trusty 14.04 has broken Docker image creation

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#1758]
The recent upgrade to Travis has broken the creation of the PyCBC Docker image https://hub.docker.com/r/pycbc/pycbc-el7/

Details and an attempted workaround (reverting to the old Travis Ubuntu image) are described in the commit https://github.com/ligo-cbc/pycbc/commit/bbb86ceae0c943e4dd152b9af97eaffa5f8bb5a9

The symptom to watch out for is the Travis build on the target ``pycbc_docker`` internally failing with the error:
```
Traceback (most recent call last):
  File "setup.py", line 337, in <module>
    VERSION = get_version_info()
  File "setup.py", line 275, in get_version_info
    with open('[secure]/version.py', 'w') as f:
IOError: [Errno 13] Permission denied: '[secure]/version.py'
```
as in [this build log](https://travis-ci.org/ligo-cbc/pycbc/jobs/247155240#L726) getting hung up on
```
The authenticity of host 'sugwg-condor.phy.syr.edu (128.230.190.43)' can't be established.
RSA key fingerprint is 3a:f0:74:5d:be:28:d9:3e:cc:ec:45:24:db:99:f8:ac.
Are you sure you want to continue connecting (yes/no)? 
```
as in [this build log.](https://travis-ci.org/ligo-cbc/pycbc/jobs/247124585#L739)

Both of these appear to be symptoms of the travis directories is not being mounted into the docker image with the correct permissions by
```
-v ~/.ssh:/home/pycbc/.ssh -v `pwd`:/pycbc:rw ${DOCKER_IMG}-tmp
```
at https://github.com/ligo-cbc/pycbc/blob/master/.travis.yml#L80

The correct long-term fix will have to wait until I get back from vacation, but likely involves fixing this line.

**Comment by duncan-brown** [comment]
This is helpful to trigger builds for testing

https://docs.travis-ci.com/user/triggering-builds/

**Comment by duncan-brown** [comment]
This is now pressing as the E@H PyCBC script no longer works:

https://travis-ci.org/ligo-cbc/pycbc/jobs/263020083

**Comment by duncan-brown** [comment]
Temporary fix for the above in https://github.com/ligo-cbc/pycbc/pull/1830/commits/d3bd58115720ca5825e4be2c2bc881716d64dc15

**Comment by duncan-brown** [comment]
The issues that need to be fixed are as follows:

 - [``pycbc_build_eah.sh``](https://github.com/ligo-cbc/pycbc/blob/master/tools/einsteinathome/pycbc_build_eah.sh) needs to be fixed so that it recognized Ubuntu 14 and used gcc 4.8 on that platform.
 - There is a problem in the native Travis VM described in https://github.com/travis-ci/travis-ci/issues/7940 that affects the Python ``boto`` package, which is a dependency of Pegasus. To fix this, the environment variable ``BOTO_CONFIG`` needs to be set to ``/dev/null``.
 - The UID and GID of the Travis user (2000:2000) do not match the UID and GID of the pycbc user inside the Docker container (1000:1000) which means that the mounted ``/pycbc`` directory cannot be written to, and the contents of ``.ssh`` cannot be accessed.

**Comment by duncan-brown** [comment]
The three issues above are fixed by https://github.com/ligo-cbc/pycbc/pull/1905
