### ISSUE TITLE
confusing error in pycbc_inference when prior not specified

### ISSUE THREAD

**Issue by vivienr** [ligo-cbc/pycbc#1950]
Hi,

the following error gets raised when running with an .ini file that does not contain any prior section:

```
Traceback (most recent call last):
  File "/Users/vivien/pe/master/bin/pycbc_inference", line 186, in <module>
    option_utils.read_args_from_config(cp)
  File "/Users/vivien/pe/master/lib/python2.7/site-packages/pycbc/inference/option_utils.py", line 121, in read_args_from_config
    tags = numpy.concatenate([tag.split("+") for tag in subsections])
ValueError: need at least one array to concatenate
```

The error could be more descriptive. Thanks !

**Comment by cdcapano** [comment]
Fixed by #1956.
