### ISSUE TITLE
cannot use the --frame-type command with pycbc_inspiral

### ISSUE THREAD

**Issue by cmbiwer** [ligo-cbc/pycbc#197]
I'm trying to use the `--frame-type` option with `pycbc_inspiral` and I'm receiving an error.

The command I ran on sugar was:
```
cd /home/cbiwer/src/cbccalibration_exe_dev/examples/workflow/er6_t1/work/main_ID0000001
pycbc_inspiral  --segment-end-pad 64 --segment-length 256 --pad-data 8 --sample-rate 4096 --segment-start-pad 64 --psd-segment-stride 128 --psd-inverse-length 16 --filter-inj-only  --psd-segment-length 256 --processing-scheme cpu --snr-threshold 5.5 --cluster-method template --approximant SPAtmplt --psd-estimation median --maximization-interval 30 --strain-high-pass 30 --order 7 --chisq-bins 16 --channel-name L1:OAF-CAL_DARM_DQ --low-frequency-cutoff 40 --gps-start-time 1102660099 --gps-end-time 1102662147 --trig-start-time 1102660091 --trig-end-time 1102662155 --output  110266/L1-INSPIRAL_KAPPA_A_0.975-1102660091-2064.xml.gz  --frame-type L1_RDS  --bank-file  L1-TMPLTBANK_SNGL-1102660163-1920.xml.gz  --user-tag KAPPA_A_0.975
```

The error was:
```
Traceback (most recent call last):
  File "/home/cbiwer/pycbc/taper_fix_20150811/bin/pycbc_inspiral", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===ee0cef', 'pycbc_inspiral')
  File "/home/cbiwer/.local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/cbiwer/.local/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/cbiwer/pycbc/taper_fix_20150811/lib/python2.6/site-packages/PyCBC-ee0cef-py2.6.egg/EGG-INFO/scripts/pycbc_inspiral", line 186, in <module>
    gwstrain = strain.from_cli(opt, DYN_RANGE_FAC)
  File "/home/cbiwer/pycbc/taper_fix_20150811/lib/python2.6/site-packages/PyCBC-ee0cef-py2.6.egg/pycbc/strain.py", line 64, in from_cli
    end_time=opt.gps_end_time+opt.pad_data)
  File "/home/cbiwer/pycbc/taper_fix_20150811/lib/python2.6/site-packages/PyCBC-ee0cef-py2.6.egg/pycbc/frame.py", line 287, in query_and_read_frame
    paths = frame_paths(frame_type, start_time, end_time)
  File "/home/cbiwer/pycbc/taper_fix_20150811/lib/python2.6/site-packages/PyCBC-ee0cef-py2.6.egg/pycbc/frame.py", line 251, in frame_paths
    gpsend=end_time)
  File "build/bdist.linux-x86_64/egg/glue/datafind.py", line 232, in find_times
  File "build/bdist.linux-x86_64/egg/glue/datafind.py", line 124, in _requestresponse
RuntimeError: Server returned code 404: Not Found404 Not Found

The server has not found anything matching the Request-URI.
```

Opening an issue to try and figure this out.

**Comment by cmbiwer** [comment]
This issue was resolved with #199.
