### ISSUE TITLE
hdf5 1.8.5 causes error if there are no triggers in a bin

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#338]
The LDG SL6 machines have hdf5-1.8.5.patch1-9.el6.x86_64 installed which causes the following error if there are no triggers in a bin:
```python
Traceback (most recent call last):
  File "/home/steven.reyes/pycbc-dev/bin/pycbc_coinc_statmap", line 4, in 
    __import__('pkg_resources').run_script('PyCBC==2040rc3', 'pycbc_coinc_statmap')
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/PyCBC-2040rc3-py2.6.egg/EGG-INFO/scripts/pycbc_coinc_statmap", line 74, in 
    f['foreground/' + k] = numpy.array([])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/usr1/steven.reyes/pip-build-BGGOAz/h5py/h5py/_objects.c:2467)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/usr1/steven.reyes/pip-build-BGGOAz/h5py/h5py/_objects.c:2424)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/h5py/_hl/group.py", line 283, in __setitem__
    ds = self.create_dataset(None, data=obj, dtype=base.guess_dtype(obj))
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/h5py/_hl/group.py", line 103, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/h5py/_hl/dataset.py", line 120, in make_new_dset
    sid = h5s.create_simple(shape, maxshape)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/usr1/steven.reyes/pip-build-BGGOAz/h5py/h5py/_objects.c:2467)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/usr1/steven.reyes/pip-build-BGGOAz/h5py/h5py/_objects.c:2424)
  File "h5py/h5s.pyx", line 99, in h5py.h5s.create_simple (/usr1/steven.reyes/pip-build-BGGOAz/h5py/h5py/h5s.c:1416)
ValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)
```

**Comment by duncan-brown** [comment]
Need to upgrade hdf5.

**Comment by duncan-brown** [comment]
The solution to this is a fix to the instructions for users running on SL6 to tell them to manually install hdf5. I will submit a patch
```shell
NAME=/path/to/virtenv
source $NAME/bin/activate
cd $NAME/src/
curl https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.12/src/hdf5-1.8.12.tar.gz > hdf5-1.8.12.tar.gz
tar -zxvf hdf5-1.8.12.tar.gz
cd hdf5-1.8.12
./configure --prefix=$NAME/opt/hdf5-1.8.12
make -j 8 install
cd $NAME
HDF5_DIR=$NAME/opt/hdf5-1.8.12 pip install h5py
deactivate
```
For users that already have a virtual environment set up on SL6 that needs repairing, they can do
```shell
pip uninstall h5py
```
and follow the instructions above. However, on the pip install, you must give --no-cache, i.e.
```shell
HDF5_DIR=$NAME/opt/hdf5-1.8.12 pip --no-cache install h5py
```
so that h5py gets rebuilt against the newly installed version and pip doesn't install the cached build.

**Comment by duncan-brown** [comment]
The instructions seem to work:
```shell
(pycbc-dev)[steven.reyes@sugar-dev3 ~]$ which ipython
~/pycbc-dev/bin/ipython
(pycbc-dev)[steven.reyes@sugar-dev3 ~]$ ipython
Python 2.6.6 (r266:84292, Nov 21 2013, 12:39:37) 
Type "copyright", "credits" or "license" for more information.

IPython 0.10 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

In [1]: import pycbc
KeyboardInterrupt

In [1]: import h5py, numpy

In [2]: f = h5py.File('test.hdf', 'w')

In [3]: f['data'] = numpy.array([], dtype=numpy.float32)

In [4]: 
Do you really want to exit ([y]/n)? y
```

**Comment by duncan-brown** [comment]
Should be solved by users following the instructions in https://github.com/ligo-cbc/pycbc/pull/341
