### ISSUE TITLE
problem with pycbc_page_foreground

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#340]
We installed hdf5 1.8.12 in @stevereyes01's virtual environment on sugar-dev3 and the workflow progressed but got stuck at pycbc_page_foreground. Running the command by hand
```shell
cd /home/steven.reyes/projects/cbc/S6_Re_analysis/search/output/work/main_ID0000001
/home/steven.reyes/pycbc-dev/bin/pycbc_page_foreground  --bank-file  H1L1-BANK2HDF-967593543-1209744.hdf  --foreground-tag full_data --trigger-file  H1L1-COMBINE_STATMAP_FULL_DATA_FULL_CUMULATIVE_CAT_123H_FULL_DATA_FULL-967593543-1209744.hdf  --single-detector-triggers  H1-HDF_TRIGGER_MERGE_FULL_DATA-967593543-1209744.hdf   L1-HDF_TRIGGER_MERGE_FULL_DATA-967593543-1209744.hdf  --output-file  H1L1-PAGE_FOREGROUND_XMLLOUDEST-967593543-1209744.xml
```
gives the error
```python
Traceback (most recent call last):
  File "/home/steven.reyes/pycbc-dev/bin/pycbc_page_foreground", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==2040rc3', 'pycbc_page_foreground')
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/PyCBC-2040rc3-py2.6.egg/EGG-INFO/scripts/pycbc_page_foreground", line 79, in <module>
    fortrigs.to_coinc_xml_object(args.output_file)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/PyCBC-2040rc3-py2.6.egg/pycbc/io/hdf.py", line 495, in to_coinc_xml_object
    bank_col_vals[name] = self.get_bankfile_array(name)
  File "/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/PyCBC-2040rc3-py2.6.egg/pycbc/io/hdf.py", line 424, in get_bankfile_array
    return self.bank_file[variable][:][self.template_id]
IndexError: arrays used as indices must be of integer (or boolean) type
```

**Comment by duncan-brown** [comment]
@stevereyes01 will re-run the entire workflow from scratch incase the HDF5 files got corrupted somehow.

**Comment by duncan-brown** [comment]
A fresh re-run with the version 1.8.12 of the HDF5 library produces the same error. The following page_foreground jobs fail with the error above:
 * http://sugar-dev3.phy.syr.edu/pegasus/u/steven.reyes/r/10/w/2/j/2867/ji/3619
 * http://sugar-dev3.phy.syr.edu/pegasus/u/steven.reyes/r/10/w/2/j/3631/ji/3621
 * http://sugar-dev3.phy.syr.edu/pegasus/u/steven.reyes/r/10/w/2/j/2539/ji/3620
@spxiwh and @ahnitz any ideas?

**Comment by spxiwh** [comment]
Trying to follow this up now. Looks like the virtual environment here is not "complete" .... not so easy to debug when that's the case. I'll start installing my own virtualenv on sugar unless someone can point me to a working version?:

```
[spxiwh@sugar-dev3 03:16 AM steven.reyes]$ source /home/steven.reyes/pycbc-dev/bin/activate
(pycbc-dev)[spxiwh@sugar-dev3 03:16 AM steven.reyes]$ pycbc_page_foreground --help
Traceback (most recent call last):
  File "/home/steven.reyes/pycbc-dev/bin/pycbc_page_foreground", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==2040rc3', 'pycbc_page_foreground')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pyRXP>=2.1.0
```

**Comment by spxiwh** [comment]
@ahnitz this makes no sense at all! The lines around this read

```
        try:
            return self.bank_file[variable][:][self.template_id]
        except IndexError:
            if len(self.template_id) == 0:
                return np.array([])
            raise
```

I don't see how the first return can possibly raise an IndexError! I tried changing except IndexError: to except: and it still fails within the try block, how is that possible!

Any ideas? I'm confused by this one!! The block in question worked in the empty array case on vulcan (I added the except bit to *make* it work).

**Comment by spxiwh** [comment]
Disregard that, template_id is in fact not zero length, so the error is raised within the except

**Comment by spxiwh** [comment]
Okay, the problem here is that the template_id and trig_id properties are both being read as floats. Not sure why this hasn't been noticed before! I'm trying to see now whether this is an issue in pycbc_page_foreground or in the code that wrote the HDF file.

**Comment by spxiwh** [comment]
It's the file. If I open Steven's statmap file I can see:

In [6]: a['foreground']['trigger_id1']
Out[6]: <HDF5 dataset "trigger_id1": shape (4,), type "<f8">

(ie. stored as a float). But if I open one of mine on vulcan:

In [3]: a['foreground']['trigger_id1']
Out[3]: <HDF5 dataset "trigger_id1": shape (49,), type "<i8">

integer!

**Comment by spxiwh** [comment]
Ahh, I see the problem. *One* of Steve's mass bin is empty, but only one of the three. The dtype of trigger_id for the empty bin is float, the non-empty bins are correctly integers. But when these are combined the dtype becomes float from the empty bin. So the fix will be to ensure that the dtype of empty arrays is correct.

**Comment by spxiwh** [comment]
#342 is now merged @stevereyes01 can you verify this fixes things for you (you will need to rerun everything after pycbc_inspiral jobs) and close the issue if it does?

**Comment by duncan-brown** [comment]
I'll start a run going to test this.

**Comment by duncan-brown** [comment]
@spxiwh by the way, I don't see the environment error your reported above. Do you have some cruft in your PATHs on sugar?

```shell
[dbrown@sugar-dev3 ~]$ source /home/steven.reyes/pycbc-dev/bin/activate
(pycbc-dev)[dbrown@sugar-dev3 ~]$ pycbc_page_foreground --help
usage: pycbc_page_foreground [-h] [--trigger-file TRIGGER_FILE]
                             [--bank-file BANK_FILE]
                             [--single-detector-triggers SINGLE_DETECTOR_TRIGGERS [SINGLE_DETECTOR_TRIGGERS ...]]
                             [--verbose] [--output-file OUTPUT_FILE]
                             [--foreground-tag FOREGROUND_TAG]
                             [--num-coincs-to-write NUM_COINCS_TO_WRITE]

optional arguments:
  -h, --help            show this help message and exit
  --trigger-file TRIGGER_FILE
  --bank-file BANK_FILE
  --single-detector-triggers SINGLE_DETECTOR_TRIGGERS [SINGLE_DETECTOR_TRIGGERS ...]
  --verbose
  --output-file OUTPUT_FILE
  --foreground-tag FOREGROUND_TAG
  --num-coincs-to-write NUM_COINCS_TO_WRITE
```

**Comment by duncan-brown** [comment]
Looks good http://sugar-dev3.phy.syr.edu/pegasus/u/dbrown/r/57/w/2/j/208/ji/112

**Comment by spxiwh** [comment]
@duncan-brown I don't see anything wrong with my env. Can you tell me what you get when you do:

import pyRXP
pyRXP.__file__

in steve's virtualenv I get nothing at all. Out of it I get the system version, which is only 1.13.

**Comment by duncan-brown** [comment]
@spxiwh that's the old PyRXP module. Try
```
(pycbc-dev)[dbrown@sugar-dev3 ~]$ python
Python 2.6.6 (r266:84292, Nov 21 2013, 12:39:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyRXPU
>>> pyRXPU.__file__
'/home/steven.reyes/pycbc-dev/lib/python2.6/site-packages/pyRXPU.so'
```

**Comment by duncan-brown** [comment]
@spxiwh you have cruft in your PYTHONPATH:
```shell
[root@sugar-dev3 ~]# su - spxiwh
MATLAB: Default version /opt/matlab_2013a is active.

error: could not lock config file /home/spxiwh/.gitconfig: File exists
error: could not lock config file /home/spxiwh/.gitconfig: File exists
[spxiwh@sugar-dev3 08:23 AM ~]$ echo $PYTHONPATH 
/opt/lscsoft/gst/lib64/python2.6/site-packages::/home/spxiwh/opt/qm/lib64/python2.6/site-packages:/home/spxiwh/opt/sphinx/lib/python2.6/site-packages:/home/spxiwh/opt/configparser/lib/python2.6/site-packages:/home/spxiwh/opt/pegasus_service/lib/python2.6/site-packages/
[spxiwh@sugar-dev3 08:24 AM ~]$ unset PYTHONPATH
[spxiwh@sugar-dev3 08:24 AM ~]$ source /home/steven.reyes/pycbc-dev/bin/activate
(pycbc-dev)[spxiwh@sugar-dev3 08:24 AM ~]$ pycbc_page_foreground --help
usage: pycbc_page_foreground [-h] [--trigger-file TRIGGER_FILE]
                             [--bank-file BANK_FILE]
                             [--single-detector-triggers SINGLE_DETECTOR_TRIGGERS [SINGLE_DETECTOR_TRIGGERS ...]]
                             [--verbose] [--output-file OUTPUT_FILE]
                             [--foreground-tag FOREGROUND_TAG]
                             [--num-coincs-to-write NUM_COINCS_TO_WRITE]

optional arguments:
  -h, --help            show this help message and exit
  --trigger-file TRIGGER_FILE
  --bank-file BANK_FILE
  --single-detector-triggers SINGLE_DETECTOR_TRIGGERS [SINGLE_DETECTOR_TRIGGERS ...]
  --verbose
  --output-file OUTPUT_FILE
  --foreground-tag FOREGROUND_TAG
  --num-coincs-to-write NUM_COINCS_TO_WRITE
```
