### ISSUE TITLE
Error in workflow generation code

### ISSUE THREAD

**Issue by duncan-brown** [ligo-cbc/pycbc#606]
```python
Traceback (most recent call last):
  File "/home/dbrown/src/pycbc-dev/bin/pycbc_make_coinc_search_workflow", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC===e1c191', 'pycbc_make_coinc_search_workflow')
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-e1c191-py2.6.egg/EGG-INFO/scripts/pycbc_make_coinc_search_workflow", line 155, in <module>
    output_dir, tags=ctags)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-e1c191-py2.6.egg/pycbc/workflow/coincidence.py", line 821, in setup_interval_coinc
    stat_files += [setup_statmap(workflow, bg_files, hdfbank, out_dir, tags=tags + [veto_name])]
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-e1c191-py2.6.egg/pycbc/workflow/coincidence.py", line 638, in setup_statmap
    return setup_background_bins(workflow, coinc_files, bank_file, out_dir, tags=tags)
  File "/home/dbrown/src/pycbc-dev/lib/python2.6/site-packages/PyCBC-e1c191-py2.6.egg/pycbc/workflow/coincidence.py", line 667, in setup_background_bins
    background_bins.remove('')
ValueError: list.remove(x): x not in list
```

**Comment by duncan-brown** [comment]
Seems to have been caused by https://github.com/ligo-cbc/pycbc/pull/595/files

**Comment by cdcapano** [comment]
Duncan, this should fix it. Replace:
```python
 background_bins.remove('')
```
with:
```python
background_bins = [x for x in background_bins if x != '']
```
at line 667 of coincidence.py.

**Comment by cdcapano** [comment]
Also, you'll need to do the same replacement at line 716.

**Comment by duncan-brown** [comment]
Thanks, pending pull at https://github.com/duncan-brown/pycbc/commit/15e26fa925d9ecca7413ac46a032c7f661061e44
