### ISSUE TITLE
The current example ini files are broken in pycbc workflow

### ISSUE THREAD

**Issue by spxiwh** [ligo-cbc/pycbc#70]
The current example ini files seem to broken in the current master of pycbc. Running them gives an error (shown below). I'm not really sure what this means ... I worry that the bitwise operation performed between two segment lists here may not be compatible with the lal.LIGOTimeGPS type. If so, that would be bad. Thoughts?

2015-06-16 18:04:53,187:INFO : Leaving split output files module.
2015-06-16 18:04:53,187:INFO : Entering injection module.
2015-06-16 18:04:53,196:INFO : Leaving injection module.
2015-06-16 18:04:53,196:INFO : Entering time slides setup module.
2015-06-16 18:04:53,604:INFO : Entering matched-filtering setup module.
2015-06-16 18:04:53,605:INFO : Adding matched-filter jobs to workflow.
2015-06-16 18:04:53,605:INFO : Setting up matched-filtering for H1.
Traceback (most recent call last):
  File "./pycbc_make_coinc_workflow", line 123, in <module>
    tags = [tag])
  File "/home/spxiwh/lscsoft_git/executables_master/lib/python2.7/site-packages/PyCBC-65a9dd-py2.7.egg/pycbc/workflow/matched_filter.py", line 119, in setup_matchedfltr_workflow
    compatibility_mode=compatibility_mode)
  File "/home/spxiwh/lscsoft_git/executables_master/lib/python2.7/site-packages/PyCBC-65a9dd-py2.7.egg/pycbc/workflow/matched_filter.py", line 221, in setup_matchedfltr_dax_generated
    compatibility_mode=compatibility_mode)
  File "/home/spxiwh/lscsoft_git/executables_master/lib/python2.7/site-packages/PyCBC-65a9dd-py2.7.egg/pycbc/workflow/jobsetup.py", line 263, in sngl_ifo_job_setup
    useSplitLists=True)
  File "/home/spxiwh/lscsoft_git/executables_master/lib/python2.7/site-packages/PyCBC-65a9dd-py2.7.egg/pycbc/workflow/core.py", line 867, in find_outputs_in_range
    overlap_windows = [abs(i.segment_list & currsegment_list) for i in overlap_files]
TypeError: in method 'LIGOTimeGPS___gt__', argument 2 of type 'LIGOTimeGPS *'

**Comment by ahnitz** [comment]
Ian, 

Yes, it looks like ligotime gps doesn't support the needed operations. 
Is it related to this request? 

https://github.com/ligo-cbc/pycbc/pull/45

Tito,

Why did we want to convert segment lists to use ligo time gps again? Shouldn't they just be integers? (well the seconds and the nanoseconds individually are integers)

**Comment by titodalcanton** [comment]
Yes it sounds related. I had no trouble running after #45 was merged though. I also find it weird that the operation would fail with LIGOTimeGPS (didn't Kipp recommend using it?). I also remember using that type in my own implementation of the aligned-spin pipeline and I think that same operation worked. Anyway if it really doesn't work I guess we can revert to int times, although I'm worried that truncating nanoseconds might bite us later on.

**Comment by titodalcanton** [comment]
Hmm, I just verified this and indeed the & operator raises Ian's error (the | operator works though). Something to ask Kipp I suppose.

**Comment by ahnitz** [comment]
TIto, I'm not sure I understand the background here. In what sense are we truncating the nanoseconds? We aren't setting it to zero anywhere, are we? If we were to leave segments as  tuple of two ints (sec, nsec), does this cause a different problem elsewhere? 

Are you referring to executables which need integer seconds (nsec = 0), such as pycbc_inspiral? If so, how does using ligotimegps change that situation?

**Comment by ahnitz** [comment]
Ok, disregard previous post, I was confused how this was working. Using LIGOTimeGPS should be the right thing I think. I'll need to think about this a bit more.

**Comment by ahnitz** [comment]
Ok I've tracked down the problem to a simpler issue. The following has the same fundamental issue. It looks like using the glue +- infinity  (which must be used in __and__) does not work with LIGOTimeGPS. The error above is a version of this 

```
from lal import LIGOTimeGPS as u
import glue.segments

a = glue.segments.segment(u(0), u(0))
b = glue.segments.segment(u(0), u(0))

l = glue.segments.segmentlist([a, b])

print l & l
```

>Traceback (most recent call last):
  File "test.py", line 9, in <module>
    print l & l
  File "/home/ahnitz/projects/bnstest/t8/local/lib64/python2.6/site-packages/glue/segments.py", line 571, in __and__
    return self.__class__(self).__iand__(other)
  File "/home/ahnitz/projects/bnstest/t8/local/lib64/python2.6/site-packages/glue/segments.py", line 561, in __iand__
    return self.__isub__(~other)
  File "/home/ahnitz/projects/bnstest/t8/local/lib64/python2.6/site-packages/glue/segments.py", line 682, in __invert__
    if self[0][0] > NegInfinity:
TypeError: in method 'LIGOTimeGPS___gt__', argument 2 of type 'LIGOTimeGPS *'

**Comment by ahnitz** [comment]
An even simpler example

```
import glue.segments, lal
print lal.LIGOTimeGPS(0, 0) < glue.segments.PosInfinity
```

**Comment by spxiwh** [comment]
So this doesn't seem to affect the HDF workflow because it [normally] runs with a pre-generated template bank, so I think it avoids this step in dax generation.

However, I have also found this same issue in pycbc_compute_durations, which certainly means that the current version of master *cannot* reproduce ihope output. I'm reverting patch #45 locally to proceed with ER7 investigations.

.... We can't really expect people to run codes like compute_durations and *every* available workflow configuration for every patch that is made, but what sort of automatic tests can we implement to try to catch this kind of issue?

**Comment by titodalcanton** [comment]
Ian, I think a lot of segment-related code (some of which was touched by https://github.com/ligo-cbc/pycbc/pull/45) is currently not covered by unit tests. Basic tests of functions like segments_to_file() and fromsegmentxml() would be able to catch some of these issues. Of course, glue should also have its own unit tests, especially the most modular stuff like segments and segmentlists. Alex, do you think it would be a lot of work to add a bit of unit tests and travis machinery to your own glue/pylal fork?

**Comment by ahnitz** [comment]
This wouldn't have been caught either by the glue unittest as they don't
use the lal LIGOTimeGPS as far as I can tell. I think he email I sent to
Karl/DASWG is the root of the issue.

There could be some more unittests in pycbc to cover some of these things.

1) generate the example workflow and make sure it reports no errors
2) perhaps some segment handling as Tito suggested

On Wed, Jun 17, 2015 at 9:49 AM, Tito Dal Canton <notifications@github.com>
wrote:

> Ian, I think a lot of segment-related code (some of which was touched by
> #45 <https://github.com/ligo-cbc/pycbc/pull/45>) is currently not covered
> by unit tests. Basic tests of functions like segments_to_file() and
> fromsegmentxml() would be able to catch some of these issues. Of course,
> glue should also have its own unit tests, especially the most modular stuff
> like segments and segmentlists. Alex, do you think it would be a lot of
> work to add a bit of unit tests and travis machinery to your own glue/pylal
> fork?
>
That should be possible, yes. They are in fact installed in the PyCBC one
as well, but their unit tests are not exersized. I really can't guarantee
that I'll have time to do this however. We might be able to find someone to
do it. I think Larne at some point will start handling some of the unittest
infrastructure, so that would be another item to add.

**Comment by ahnitz** [comment]
Also, Ian

Can you do a pull request with your reverted patches? I think we should fix
master at least, even if the segment is not ideal, at least until we figure
out how to fix this. I hope that this is something Karl can fix, but we'll
see what his response his.

-Alex

**Comment by titodalcanton** [comment]
BTW Ian, it looks like you only need to revert one change I made in fromsegmentxml(): replace the instantiation of LIGOTimeGPS for the segment boundaries with either floats or just seg.start_time and seg.end_time (as it was before).

Alex: I mean we need unit tests which *do* use LIGOTimeGPS, as well as other reasonable time representations. The tests must prove that the segment code works for all of them. Also, I'd be happy to work more on tests, but I only can once I'm done with the defence unfortunately.

**Comment by ahnitz** [comment]
On Wed, Jun 17, 2015 at 10:00 AM, Tito Dal Canton <notifications@github.com>
wrote:

> BTW Ian, it looks like you only need to revert one change I made in
> fromsegmentxml(): replace the instantiation of LIGOTimeGPS for the segment
> boundaries with either floats or just seg.start_time and seg.end_time (as
> it was before).
>
> Alex: I mean we need unit tests which *do* use LIGOTimeGPS, as well as
> other reasonable time representations. The tests must prove that the
> segment code works for all of them.
>
Yes, you are absolutely right.

> Also, I'd be happy to work more on tests, but I only can once I'm done
> with the defence unfortunately.
>
 I understand. Best of luck to you.

**Comment by ahnitz** [comment]
After Karl's patch to lalsuite I get,

```
2015-06-17 23:00:49,407:INFO : Leaving segment generation module
2015-06-17 23:00:49,407:INFO : Entering datafind module
2015-06-17 23:00:49,408:INFO : Starting datafind with setup_datafind_runtime_generated
2015-06-17 23:00:49,408:INFO : Setting up connection to datafind server.
2015-06-17 23:00:49,408:INFO : Querying datafind server for all science segments.
2015-06-17 23:00:53,859:INFO : setup_datafind_runtime_generated completed
2015-06-17 23:00:53,859:INFO : Checking science segments against datafind output....
2015-06-17 23:00:53,869:INFO : Datafind segments calculated.....
2015-06-17 23:00:53,869:INFO : Any errors directly following this message refer to times that the segment server says are science, but datafind cannot findframes for:
2015-06-17 23:00:53,870:ERROR : IFO V1's science segments are completely missing.
2015-06-17 23:00:53,870:INFO : Done checking, any discrepancies are reported above.
2015-06-17 23:00:53,870:INFO : Verifying that all frames exist on disk.
2015-06-17 23:01:03,315:INFO : Finished checking frames.
2015-06-17 23:01:03,351:INFO : Leaving datafind module
2015-06-17 23:01:03,362:INFO : Entering template bank generation module.
2015-06-17 23:01:03,363:INFO : Adding template bank jobs to workflow.
2015-06-17 23:01:04,590:INFO : Leaving template bank generation module.
2015-06-17 23:01:04,591:INFO : Entering split output files module.
2015-06-17 23:01:04,591:INFO : Leaving split output files module.
2015-06-17 23:01:04,591:INFO : Entering injection module.
2015-06-17 23:01:04,693:INFO : Leaving injection module.
2015-06-17 23:01:04,693:INFO : Entering time slides setup module.
2015-06-17 23:01:06,557:INFO : Entering matched-filtering setup module.
2015-06-17 23:01:06,558:INFO : Adding matched-filter jobs to workflow.
2015-06-17 23:01:06,558:INFO : Setting up matched-filtering for V1.
2015-06-17 23:01:06,594:INFO : Setting up matched-filtering for H1.
2015-06-17 23:01:07,144:INFO : Setting up matched-filtering for L1.
2015-06-17 23:01:07,698:INFO : Leaving matched-filtering setup module.
2015-06-17 23:01:07,699:INFO : Entering coincidence setup module.
Traceback (most recent call last):
  File "/home/ahnitz/projects/verify/t1/v/bin/pycbc_make_coinc_workflow", line 4, in <module>
    __import__('pkg_resources').run_script('PyCBC==155928', 'pycbc_make_coinc_workflow')
  File "/home/ahnitz/projects/verify/t1/v/lib/python2.6/site-packages/pkg_resources/__init__.py", line 723, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ahnitz/projects/verify/t1/v/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1636, in run_script
    exec(code, namespace, namespace)
  File "/home/ahnitz/projects/verify/t1/v/lib/python2.6/site-packages/PyCBC-155928-py2.6.egg/EGG-INFO/scripts/pycbc_make_coinc_workflow", line 170, in <module>
    timeSlideTags=timeSlideTags)
  File "/home/ahnitz/projects/verify/t1/v/lib64/python2.6/site-packages/PyCBC-155928-py2.6.egg/pycbc/workflow/coincidence.py", line 127, in setup_coincidence_workflow
    parallelize_split_input=parallelize_split_input)
  File "/home/ahnitz/projects/verify/t1/v/lib64/python2.6/site-packages/PyCBC-155928-py2.6.egg/pycbc/workflow/coincidence.py", line 287, in setup_coincidence_workflow_ligolw_thinca
    time_slide_dict.values(), extentlimit=max_extent, verbose=False)
  File "/home/ahnitz/projects/verify/t1/v/lib64/python2.6/site-packages/pycbc_pylal-0.9.1-py2.6-linux-x86_64.egg/pylal/ligolw_cafe.py", line 547, in ligolw_cafe
    split_bins(packer, extentlimit, verbose = verbose)
  File "/home/ahnitz/projects/verify/t1/v/lib64/python2.6/site-packages/pycbc_pylal-0.9.1-py2.6-linux-x86_64.egg/pylal/ligolw_cafe.py", line 357, in split_bins
    extents = [origbin.extent[0]] + [lsctables.LIGOTimeGPS(origbin.extent[0] + i * float(abs(origbin.extent)) / n) for i in range(1, n)] + [origbin.extent[1]]
ValueError: 971613874.000000000

```

**Comment by titodalcanton** [comment]
Sounds like ligolw_cafe is trying to instantiate a lsctables.LIGOTimeGPS from a lal.LIGOTimeGPS. I guess one could fix that in lsctables, in principle it should just work.

**Comment by titodalcanton** [comment]
Or maybe we could just remove this try statement in glue and just import the lal LIGOTimeGPS?

https://github.com/ligo-cbc/pycbc-glue/blob/master/glue/ligolw/lsctables.py#L44

**Comment by ahnitz** [comment]
Tito,

I've tested your proposed change and it works for me.

In conjunction with,

https://bugs.ligo.org/redmine/issues/2215

I was able to generated the example workflow again. I'll prepare a pull
request to make the change to pycbc-glue.

**Comment by ahnitz** [comment]
The example ini files now work for me, so unless someone is having a different exper

**Comment by ahnitz** [comment]
After the last fix that Tito approved, and running from the latest master of lalsuite, the example ini file now seems to work for me. So for the time being, I'll close this issue.
