### ISSUE TITLE
pycbc_make_conic_search_workflow gives an error for a request memory config override for statmap

### ISSUE THREAD

**Issue by lenona** [ligo-cbc/pycbc#765]
When you try to run a generate workflow script with the config override

```"pegasus_profile-statmap:condor|request_memory:500000" \```

it produces the error

```
Traceback (most recent call last):
  File "<string>", line 59, in <module>
  File "/home/amber.lenon/pycbc-dev2.6/src/pycbc/tools/static/build/pycbc_make_coinc_search_workflow/out00-PYZ.pyz/pycbc.workflow.core", line 380, in __init__
  File "/home/amber.lenon/pycbc-dev2.6/src/pycbc/tools/static/build/pycbc_make_coinc_search_workflow/out00-PYZ.pyz/pycbc.workflow.configuration", line 197, in from_args
  File "/home/amber.lenon/pycbc-dev2.6/src/pycbc/tools/static/build/pycbc_make_coinc_search_workflow/out00-PYZ.pyz/pycbc.workflow.configuration", line 135, in __init__
  File "/home/amber.lenon/pycbc-dev2.6/src/pycbc/tools/static/build/pycbc_make_coinc_search_workflow/out00-PYZ.pyz/pycbc.workflow.configuration", line 422, in split_multi_sections
  File "/home/amber.lenon/pycbc-dev2.6/src/pycbc/tools/static/build/pycbc_make_coinc_search_workflow/out00-PYZ.pyz/pycbc.workflow.configuration", line 458, in add_options_to_section
ValueError: Option exists in both original ConfigParser section [pegasus_profile-statmap] and input list: condor|request_memory
```

**Comment by spxiwh** [comment]
Okay, this is an odd one. Because you have:

```
[pegasus_profile-statmap&pegasus_profile-statmap_inj]
condor|request_memory = 15000
```
The code deals with the overrides *before* splitting this into two options (one in pegasus_profile-statmap and one in pegasus_profile-statmap_inj). It then stops because it thinks you've given an option twice. The short solution would be to remove this from the ini file, so just set

```
[pegasus_profile-statmap_inj]
condor|request_memory = 15000
```

The longer solution is a code rearrangement. Here is some code from pycbc/pycbc/workflow/configuration.py:

```
        self.read_ini_file(configFiles)

        # Do overrides first
        for override in overrideTuples:
            if len(override) not in [2,3]:
                print override
                errMsg = "Overrides must be tuples of length 2 or 3."
                errMsg = "Got %s." %(str(override))
                raise ValueError(errMsg)
            section = override[0]
            option = override[1]
            value = ''
            if len(override) == 3:
                value = override[2]
            # Check for section existence, create if needed
            if not self.has_section(section):
                self.add_section(section)
            self.set(section, option, value)

        # Replace exe macros with full paths
        self.perform_exe_expansion()

        # Split sections like [inspiral&tmplt] into [inspiral] and [tmplt]
        self.split_multi_sections()
```

Can you try rearranging this according to:

```
        self.read_ini_file(configFiles)

        # Replace exe macros with full paths
        self.perform_exe_expansion()

        # Split sections like [inspiral&tmplt] into [inspiral] and [tmplt]
        self.split_multi_sections()

        # Do overrides from command line
        for override in overrideTuples:
            if len(override) not in [2,3]:
                print override
                errMsg = "Overrides must be tuples of length 2 or 3."
                errMsg = "Got %s." %(str(override))
                raise ValueError(errMsg)
            section = override[0]
            option = override[1]
            value = ''
            if len(override) == 3:
                value = override[2]
            # Check for section existence, create if needed
            if not self.has_section(section):
                self.add_section(section)
            self.set(section, option, value)
```

and see if that fixes the problem?

**Comment by duncan-brown** [comment]
@soumide1102 please can you try the fix that @spxiwh suggests?

**Comment by soumide1102** [comment]
@duncan-brown @spxiwh  I have tested the short and long solutions and both worked. Should I create a pull request with the rearranged pycbc/pycbc/workflow/configuration.py code (ie. the longer solution)?

**Comment by spxiwh** [comment]
Thanks @soumide1102. Yes please create a pull request with the longer solution and assign to me.

Cheers
Ian

**Comment by spxiwh** [comment]
This is fixed now. So closing this.
